# permissions for end users to view customecrddemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customecrddemo-viewer-role
rules:
- apiGroups:
  - apps.geoff.crd.demo
  resources:
  - customecrddemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.geoff.crd.demo
  resources:
  - customecrddemoes/status
  verbs:
  - get
