# permissions for end users to edit customecrddemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customecrddemo-editor-role
rules:
- apiGroups:
  - apps.geoff.crd.demo
  resources:
  - customecrddemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.geoff.crd.demo
  resources:
  - customecrddemoes/status
  verbs:
  - get
