---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.geoff.crd.demo
  resources:
  - customecrddemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.geoff.crd.demo
  resources:
  - customecrddemoes/finalizers
  verbs:
  - update
- apiGroups:
  - apps.geoff.crd.demo
  resources:
  - customecrddemoes/status
  verbs:
  - get
  - patch
  - update
